### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by dpshelio** [cozheyuanzhangde/Invariant-TemplateMatching#1]
Hi @cozheyuanzhangde, I work with some researchers at a UK university that are interested to use your algorithm. However, the repository doesn't include a license and that would stop them to be able to use it or even contribute back.

Github has a [choose a license page](https://choosealicense.com/) with the pros/cons of the different options. [Adding a license is very easy from the github interface](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository).

Thanks.

**Comment by dpshelio** [comment]
That was quick!! Thanks :tada: 
3093894a00cc68fe420626b3183b37043b61d304 closes this!

**Comment by cozheyuanzhangde** [comment]
No problem! Thanks for reminding me to add a license!
